---
- name: Copy URL ou GIT
  hosts: all
  vars:
    git_var: https://github.com/Frimouss/it_vunerability/tree/master
    urls:
    - https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Ansible_logo.svg/1664px-Ansible_logo.svg.png
    - https://raw.githubusercontent.com/cdufour/devops-squad/main/exos.txt
    endpoint: https://jsonplaceholder.typicode.com/posts
    members: ['Damtoti','Nathe','Damien','Pierre']
  tasks:

  - name: git clone du code source
    git:
      repo: "{{ git_var }}"
      dest: /home/{{ item }}/git/
    loop: "{{ members }}"

  - name: télécharge ressource
    get_url:
      url: "{{ item }}"
      dest: /home/Pierre/URL/
      mode: 400
    loop: "{{ urls }}"

  - name: requête sur {{ endpoint }}
    uri:
      url: "{{ endpoint }}"
      method: GET
    register: validation

  - name:
    debug: var=validation
...
